import Head from 'next/head'

import { useState, useEffect } from 'react';
import axios from 'axios';

export default function Home() {

 

  const [ isLoading, setIsLoading ] = useState(false)
  const [ movies, setMovies] = useState([])
  const [movieName, setMovieName] = useState('');
  const [ isSearching, setIsSearching] = useState(false)

  
  const [ moviesCategories, setMoviesCategories] = useState([])
  const [ series, setSeries] = useState([])


   const FetchCategories = async () => {
			console.log(movieName);
			const { data } = await axios.get(
				`http://www.omdbapi.com/?s=title&apikey=b1d50b62`
			);

			console.log(data.Search);
			setMoviesCategories(data.Search);
		};



  const FetchMovies = async () => {
	 
	setIsSearching(true)
	console.log(movieName);
	  const { data } = await axios.get(
			`http://www.omdbapi.com/?s=${movieName}&apikey=b1d50b62`
		);

		console.log(data.Search);
		setMovies(data.Search)
		
  }

  useEffect(() => {

		FetchCategories()

  }, [])

  return (
		<div>
			<Head>
				<title>Test App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div>
				<nav className="navbar flex items-center justify-center lg:justify-start px-4 overflow-hidden">
					<button className="bg-grey text-white font-semibold  py-4 px-4 border border-white rounded">
						MyTestApp
					</button>
				</nav>
				<div className="hero text-white px-8 pt-16 text-center lg:text-left overflow-hidden ">
					<h1>
						Watch
						<br />
						Something
						<br />
						Incredible.
					</h1>
				</div>
			</div>

			<div className="m-4">
				<h4>Search</h4>

				<div>
					<div className="input_div">
						<input
							type="text"
							placeholder="Search"
							value={movieName}
							onChange={(e) => setMovieName(e.target.value)}
						/>
						<img
							onClick={FetchMovies}
							className="inline w-8 search"
							src="img/search.png"
							alt=""
						/>
					</div>
				</div>
			</div>
			{!isSearching && (
				<div className="p-4">
					<h3 className="py-4">Movie Categories</h3>
					<div className="grid w-full gap-6 grid-col-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 my-4">
						{moviesCategories.slice(0, 4).map((movie) => (
							<div
								className="w-72 h-72 bg-black md:mx-0 mx-auto my-3 rounded overflow-hidden"
								key={movie.imdbID}
							>
								<img
									src={movie.Poster}
									className="w-full max-h-60 object-fit"
									alt={movie.Title}
								/>
								<div className="bg-grey text-white p-2 text-center h-7 z-10">
									<p>{movie.Title}</p>
								</div>
							</div>
						))}
					</div>
				</div>
			)}

			{isSearching && (
				<div className="p-4">
					<h3 className="py-4"> Search Results of &#39;{movieName}&#39;</h3>
					<div className="grid w-full gap-6 grid-col-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 my-4">
						{movieName ? (
							movies.map((movie) => (
								<div
									className="w-72 h-72 bg-black md:mx-0 mx-auto my-3 rounded overflow-hidden"
									key={movie.imdbID}
								>
									<img
										src={movie.Poster}
										className="w-full max-h-60 object-fit "
										alt={movie.Title}
									/>
									<div className="bg-grey text-white p-2 text-center h-7 z-10">
										<p>{movie.Title}</p>
									</div>
								</div>
							))
						) : (
							<p>Movies Loading...</p>
						)}
					</div>
				</div>
			)}
		</div>
	);
}
